services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - ./front:/usr/src/app
    ports:
      - "3000:3000"
    restart: unless-stopped
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - ./back/.env
    environment:
      - NODE_ENV= production
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./back:/usr/src/app
    ports:
      - "3030:3030"
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_transcendence
    ports:
      - "31415:5432"
    volumes:
      - ./database-data:/var/lib/postgresql/data
    container_name: db_app