services:
  frontend:
    image: front-image # nom de l'image
    container_name: front-container # nom du containeur
    volumes:
      - ./front/src:/app/cache/src   #./chemin_local:chemin_dans_le_containeur
    build:
      context: ./front #ou se trouve le dockerfile
      dockerfile: Dockerfile #le dockerfile
    restart: unless-stopped # la stratégie redémarre un conteneur quel que soit le code de sortie, mais arrête de redémarrer lorsque le service est arrêté ou supprimé.
    command: npm start # lance directement la commande npm start dans le containeur
    ports:
        - "3000:3000" #sur le port 3000
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - ./back/.env
    environment:
      - NODE_ENV= production
    ports:
      - "3030:3030"
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_transcendence
    container_name: db_app
